# LAB-01: Introduction to Python for Data Analysis

**Aim**: Familiarization with Python as an effective tool for handling and analyzing data, using NumPy and Pandas.

## Experiment-1
Write a Python program to Create a NumPy array using a Python list, Display the array and print the shape and data type of the array.

In [1]:
import numpy as np

# Create array from list
my_list = [10, 20, 30, 40, 50]
arr = np.array(my_list)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


## Experiment-2
Write a program to Create a 3x4 matrix of zeros, create a 2x5 matrix of ones and print both matrices and their shapes.

In [2]:
# Matrix of zeros
zeros_mat = np.zeros((3, 4))
print("Zeros Matrix:\n", zeros_mat)
print("Shape of Zeros Matrix:", zeros_mat.shape)

print("\n")

# Matrix of ones
ones_mat = np.ones((2, 5))
print("Ones Matrix:\n", ones_mat)
print("Shape of Ones Matrix:", ones_mat.shape)

Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of Zeros Matrix: (3, 4)


Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape of Ones Matrix: (2, 5)


## Experiment-3
Write a program to Create a NumPy array of numbers from 1 to 12, Reshape the array into a 3x4 matrix and display the original and reshaped array along with their shapes.

In [3]:
# Array from 1 to 12
arr_1_to_12 = np.arange(1, 13)
print("Original Array:", arr_1_to_12)
print("Original Shape:", arr_1_to_12.shape)

print("\n")

# Reshaping
reshaped_arr = arr_1_to_12.reshape(3, 4)
print("Reshaped Matrix:\n", reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)


Reshaped Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


## Experiment-4
Write a program to create a NumPy array of 10 random integers, Find the minimum, maximum, mean, and sum of the array.

In [4]:
# Random integers
random_arr = np.random.randint(1, 100, size=10)
print("Random Array:", random_arr)

# Statistical properties
print("Minimum:", random_arr.min())
print("Maximum:", random_arr.max())
print("Mean:", random_arr.mean())
print("Sum:", random_arr.sum())

Random Array: [53 94 53 91  8 98 49  6 15 59]
Minimum: 6
Maximum: 98
Mean: 52.6
Sum: 526


## Experiment-5
Write a Python program to create a Pandas DataFrame using a dictionary containing student names and marks. Display the DataFrame and print the data types (dtypes) of each column.

In [5]:
import pandas as pd

# Dictionary to DataFrame
data = {
    'StudentName': ['Alice', 'Bob', 'Charlie', 'David'],
    'Marks': [85, 92, 78, 88]
}

df_students = pd.DataFrame(data)
print("DataFrame:\n", df_students)
print("\nData Types:\n", df_students.dtypes)

DataFrame:
   StudentName  Marks
0       Alice     85
1         Bob     92
2     Charlie     78
3       David     88

Data Types:
 StudentName    object
Marks           int64
dtype: object


## Experiment-6
Write a program to read a CSV file using read_csv(). Display the first 5 records using head() and display the last 5 records using tail() method.
*(Using the local Iris.csv dataset)*

In [6]:
# Read CSV
df_iris = pd.read_csv("../Iris.csv")

print("First 5 records:")
display(df_iris.head())

print("\nLast 5 records:")
display(df_iris.tail())

First 5 records:


,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa



Last 5 records:


,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica


## Experiment-7
Write a Python program to Load a dataset using Pandas Display dataset structure using info() and identify the number of rows, columns, and missing values.

In [7]:
# Info and structural details
print("Dataset Structure (info):\n")
df_iris.info()

print("\nShape (Rows, Columns):", df_iris.shape)

print("\nMissing Values per column:\n", df_iris.isnull().sum())

Dataset Structure (info):

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

Shape (Rows, Columns): (150, 6)

Missing Values per column:
 Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64


## Experiment-8
Write a program to Read a CSV file into a DataFrame Display statistical summary using describe() Interpret mean, standard deviation, minimum, and maximum values.

In [8]:
# Statistical Summary
display(df_iris.describe())

print("\nInterpretation:")
print("- describe() computes various summary statistics for numerical columns, excluding NaN values.")
print("- It provides the Mean (average value), Standard Deviation (dispersion relative to the mean), and outliers mapping via Min/Max/Quartiles.")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000



Interpretation:
- describe() computes various summary statistics for numerical columns, excluding NaN values.
- It provides the Mean (average value), Standard Deviation (dispersion relative to the mean), and outliers mapping via Min/Max/Quartiles.
